#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  PLATFORM="linux-amd64"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  PLATFORM="darwin-amd64"
else
  echo "Unsupported platform: $OSTYPE"
  exit 1
fi

NEXUS="http://nexus.oncue.verizon.net/nexus/"
PROJECT="$NEXUS/content/groups/internal/verizon/inf/nelson/cli"
VERSION=$(curl $PROJECT/ | sed -n -e 's#.*>\([^>]*\)/</a></td>#\1#p' | tail -1)
ARTIFACT_BASE="nelson-${PLATFORM}-${VERSION}"
URI_BASE=$PROJECT/$VERSION/$ARTIFACT_BASE

echo "====>> Downloading and extracting nelson-${PLATFORM}-${VERSION}"

cd /tmp
curl -sSL ${URI_BASE}.tar.gz -o ${ARTIFACT_BASE}.tar.gz

echo "====>> Checking shasum"
curl -sSL ${URI_BASE}.tar.gz.sha1 -o ${ARTIFACT_BASE}.tar.gz.sha1
echo "  ${ARTIFACT_BASE}.tar.gz" >> ${ARTIFACT_BASE}.tar.gz.sha1
shasum -c ${ARTIFACT_BASE}.tar.gz.sha1

echo "====>> Extracting"

tar xzf ${ARTIFACT_BASE}.tar.gz

echo "====>> Copying nelson to /usr/local/bin"

if [ -w /usr/local/bin ]; then
    SUDO=""
else
    SUDO="sudo "
fi
$SUDO cp nelson /usr/local/bin
